In [30]:
import pandas as pd

df_lego_inicial = pd.read_csv('Set_Lanzanzados.csv')

df_lego_inicial.head()

/var/folders/41/9xs275yn7jxbs_h59j3pq3sw0000gn/T/ipykernel_3002/3189011234.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lego_inicial = pd.read_csv('Set_Lanzanzados.csv')

,SetID,Number,Variant,YearFrom,Category,Theme,ThemeGroup,Subtheme,SetName,Image,...,WantedPriority,Unnamed: 49,Flag2,Flag3,Flag4,Flag5,Flag6,Flag7,Flag8,UserNotes
0,22667,1,1,1965,Normal,Samsonite,Vintage,Basic Set,Gears,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22683,1,3,1967,Normal,Samsonite,Vintage,Basic Set,Promotional Set No. 1 (Kraft Velveeta),X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7465,1,7,1973,Normal,Universal Building Set,Basic,NaN,Basic Set,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7693,1,8,1970,Normal,Minitalia,Vintage,NaN,Small house set,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22697,1,9,1969,Normal,System,Basic,Basic Set,Set No 1 - Quaker/Life Cereal,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_lego_inicial

In [ ]:
# Lista de temas elegidos para el proyecto
selected_themes = [
    'Animal Crossing', 'Architecture', 'Art', 
    'Avatar: The Last Airbender', 'Avatar',
    'The LEGO Batman Movie', 'Batman', 'Botanicals',
    'BrickHeadz', 'World City', 'City', 'Classic',
    'Creator', 'Creator Expert', 'DC Super Hero Girls', 'DC Comics Super Heroes',
    'Despicable Me', 'Disney', 'Dots', 'Dreamzzz', 'DREAMZzz',
    'Duplo', 'Education', 'Friends', 'Fortnite', "Gabby's Dollhouse",
    'Harry Potter', 'Icons', 'Ideas', 'Indiana Jones', 'Jurassic World',
    'The Lord of the Rings', 'Marvel Super Heroes', 'Minecraft',
    'Collectable Minifigures', 'Monkie Kid', 'The LEGO Ninjago Movie', 'Ninjago',
    'Powered Up', 'Serious Play', 'Sonic the Hedgehog', 'Speed Champions',
    'Spider-Man', 'Star Wars', 'Super Mario', 'Technic', 'The Legend of Zelda',
    'Wednesday', 'Wicked',
]

In [32]:
# Filtro el dataset para que solo contenga las filas de los temas seleccionados
df_lego_work = df_lego_inicial[df_lego_inicial['Theme'].isin(selected_themes)]

In [33]:
df_lego_work

,SetID,Number,Variant,YearFrom,Category,Theme,ThemeGroup,Subtheme,SetName,Image,...,WantedPriority,Unnamed: 49,Flag2,Flag3,Flag4,Flag5,Flag6,Flag7,Flag8,UserNotes
48,7530,10,2,1973,Normal,Duplo,Pre-school,NaN,Pre-School Set,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,7531,20,2,1973,Normal,Duplo,Pre-school,NaN,Building Set,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,1119,28,1,1979,Normal,Duplo,Pre-school,NaN,Nursery Furniture,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,7532,30,2,1973,Normal,Duplo,Pre-school,NaN,Building Set,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,1382,32,1,1979,Normal,Duplo,Pre-school,NaN,Living Room Furniture,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21328,22656,WISHINGWELL,1,2013,Other,Friends,Modern day,Promotional,Wishing Well,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21335,30208,XWING,2,2019,Other,Star Wars,Licensed,Promotional,X-wing Trench Run,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21336,29327,XWING,1,2019,Other,Star Wars,Licensed,Promotional,Mini X-wing Fighter,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21337,22978,YODA,1,2013,Other,Star Wars,Licensed,Promotional,"Yoda minifig, NY I Heart Torso",X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21338,22776,YODACHRON,1,2013,Other,Star Wars,Licensed,Promotional,Holocron Chamber,X,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
columns_to_drop = ['Own', 'Want', 'Unnamed: 49', 'Flag2', 'Flag3', 'Flag4', 'Flag5', 'Flag6', 'Flag7', 'Flag8', 'UserNotes',"Variant", "ThemeGroup", "EAN", "UPC", "UKRetailPrice",
    'QtyOwned','QtyOwnedNew','QtyOwnedUsed','QtyWanted','WantedPriority',"CARetailPrice", "DERetailPrice", "AdditionalImageCount", "InstructionsCount","USDateAdded", "USDateRemoved", "Designers", "Image", "USItemNumber", "EUItemNumber"]
df_lego_work = df_lego_work.drop(columns=columns_to_drop)

In [35]:
df_lego_work.to_csv("df_lego_work.csv", index=False)

In [36]:
df_lego_work

,SetID,Number,YearFrom,Category,Theme,Subtheme,SetName,ImageFilename,USRetailPrice,Pieces,...,AgeMin,AgeMax,OwnCount,WantCount,Released,Rating,BrickLinkSoldPriceNew,BrickLinkSoldPriceUsed,LaunchDate,ExitDate
48,7530,10,1973,Normal,Duplo,NaN,Pre-School Set,NaN,NaN,17.0,...,NaN,NaN,16,22,X,0,NaN,NaN,NaN,NaN
71,7531,20,1973,Normal,Duplo,NaN,Building Set,NaN,NaN,25.0,...,NaN,NaN,17,24,X,0,NaN,NaN,NaN,NaN
81,1119,28,1979,Normal,Duplo,NaN,Nursery Furniture,028-1,NaN,7.0,...,NaN,NaN,50,31,X,0,NaN,11.72,NaN,NaN
85,7532,30,1973,Normal,Duplo,NaN,Building Set,NaN,NaN,29.0,...,NaN,NaN,17,23,X,0,NaN,NaN,NaN,NaN
87,1382,32,1979,Normal,Duplo,NaN,Living Room Furniture,032-1,NaN,14.0,...,NaN,NaN,69,27,X,0,NaN,10.52,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21328,22656,WISHINGWELL,2013,Other,Friends,Promotional,Wishing Well,WISHINGWELL-1,NaN,28.0,...,NaN,NaN,216,506,X,0,NaN,NaN,NaN,NaN
21335,30208,XWING,2019,Other,Star Wars,Promotional,X-wing Trench Run,XWING-2,NaN,52.0,...,NaN,NaN,133,747,X,0,14.7,21.16,NaN,NaN
21336,29327,XWING,2019,Other,Star Wars,Promotional,Mini X-wing Fighter,XWING-1,NaN,60.0,...,8.0,NaN,141,582,X,0,NaN,NaN,NaN,NaN
21337,22978,YODA,2013,Other,Star Wars,Promotional,"Yoda minifig, NY I Heart Torso",YODA-1,NaN,3.0,...,NaN,NaN,249,1967,X,4,2826.3,NaN,NaN,NaN
21338,22776,YODACHRON,2013,Other,Star Wars,Promotional,Holocron Chamber,YODACHRON-1,NaN,408.0,...,NaN,NaN,209,1831,X,0,4885.9,320.00,NaN,NaN